id: P166A94E4
initial_creation_type: ocr
source_metadata:
  volumes:
    0044d711dac34fc88636463b78a2c3c0:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: སངས་རྒྱས་རྗེས་སུ་དྲན་པའི་འགྲེལ་པ།
      total_pages: 1498
      volume_number: 65
